version: "3.8"

services:
  web:
    build: . # O Dockerfile deve estar na raiz do projeto
    ports:
      - "8080:80" # Mapeia a porta 80 do contêiner para a porta 8080 do host

  db:
    image: mysql:5.7 # Imagem do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Senha do usuário root
      MYSQL_DATABASE: stockdb # Nome do banco de dados a ser criado
      MYSQL_USER: user # Nome do usuário do banco de dados
      MYSQL_PASSWORD: userpassword # Senha do usuário
    volumes:
      - db_data:/var/lib/mysql # Volume para persistência de dados
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Imagem do phpMyAdmin
    environment:
      PMA_HOST: db # Nome do serviço do MySQL
      PMA_PORT: 3306 # Porta padrão do MySQL
      PMA_USER: user # Nome do usuário do banco de dados
      PMA_PASSWORD: userpassword # Senha do usuário
    ports:
      - "8081:80" # Mapeia a porta 80 do phpMyAdmin para a porta 8081 do host
    depends_on:
      - db # Garante que o MySQL esteja em execução antes do phpMyAdmin

volumes:
  db_data: # Declaração do volume persistente

